import fs from 'node:fs'
import path from 'node:path'
import esbuild from 'esbuild'

interface DiscoveredRoute {
  sourceFile: string
  h3Pattern: string
  method: string
}

function toH3Pattern(segments: string[]): string {
  const converted = segments.map((seg) => {
    const dynamic = seg.match(/^\[(\w+)\]$/)
    return dynamic ? `:${dynamic[1]}` : seg
  })
  return '/' + converted.join('/')
}

function walk(dir: string, baseDir: string, routes: DiscoveredRoute[]) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name)

    if (entry.isDirectory()) {
      walk(fullPath, baseDir, routes)
      continue
    }
    if (!/\.(ts|js)$/.test(entry.name)) continue

    const relPath = path.relative(baseDir, fullPath)
    const withoutExt = relPath.replace(/\.(ts|js)$/, '')
    const parts = withoutExt.split(path.sep)

    let method = 'all'
    const last = parts[parts.length - 1]
    const methodMatch = last.match(/^(.+)\.(get|post|put|patch|delete)$/)
    if (methodMatch) {
      parts[parts.length - 1] = methodMatch[1]
      method = methodMatch[2]
    }
    if (parts[parts.length - 1] === 'index') parts.pop()

    routes.push({
      sourceFile: fullPath,
      h3Pattern: toH3Pattern(parts) || '/',
      method,
    })
  }
}

/**
 * Scans `src/server/api`, bundles every handler into `<outDir>/_api/`
 * (transpiling TS, resolving local imports), and generates a
 * standalone H3 server entry that imports the bundled files via
 * relative paths — self-contained, portable to any machine.
 */
export function generateServerEntry(apiDir: string, outDir: string): string {
  const routes: DiscoveredRoute[] = []
  if (fs.existsSync(apiDir)) walk(apiDir, apiDir, routes)

  const apiOutDir = path.join(outDir, '_api')
  fs.mkdirSync(apiOutDir, { recursive: true })

  const imports: string[] = []
  const registrations: string[] = []

  routes.forEach((route, i) => {
    const relFromApiDir = path.relative(apiDir, route.sourceFile)
    const bundledRelPath = relFromApiDir.replace(/\.(ts|js)$/, '.mjs')
    const bundledFullPath = path.join(apiOutDir, bundledRelPath)

    esbuild.buildSync({
      entryPoints: [route.sourceFile],
      outfile: bundledFullPath,
      bundle: true,
      platform: 'node',
      format: 'esm',
      target: 'node20',
      external: ['h3', 'solid-vue', 'solid-vue/server'],
    })

    const importPath = './' + path.relative(outDir, bundledFullPath).replace(/\\/g, '/')
    imports.push(`import handler${i} from '${importPath}'`)
    registrations.push(`app.${route.method}('${route.h3Pattern}', handler${i})`)
  })

  return `// Auto-generated by Solid-Vue. Do not edit by hand.
import { H3 } from 'h3'
${imports.join('\n')}

export const app = new H3()
${registrations.join('\n')}
`
}