import fs from 'node:fs'
import path from 'node:path'
import { execSync, spawnSync } from 'node:child_process'
import chalk from 'chalk'

export default function deployCloudflareWorker(cwd) {
  console.log(chalk.blue.bold('\n🚀 Deploying to Cloudflare Workers...'))

  const pkgPath = path.join(cwd, 'package.json')
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'))

  // 1. Pastikeun wrangler kainstal
  const hasWrangler = pkg.devDependencies?.wrangler || pkg.dependencies?.wrangler
  if (!hasWrangler) {
    console.log(chalk.gray('   Installing wrangler...'))
    try {
      execSync('npm install -D wrangler', { stdio: 'inherit', cwd })
    } catch (err) {
      console.error(chalk.red.bold('\n❌ Failed to install wrangler:'))
      console.error(chalk.red(err.message))
      return
    }
  }

  // 2. Build
  console.log(chalk.gray('\n   Building project...'))
  try {
    execSync('npm run build', { stdio: 'inherit', cwd })
  } catch {
    console.error(chalk.red.bold('\n❌ Build failed. Fix the errors above before deploying.'))
    return
  }

  const distDir = path.join(cwd, 'dist')
  if (!fs.existsSync(distDir)) {
    console.error(chalk.red.bold('\n❌ dist/ not found after build. Check your build script.'))
    return
  }

  // 3. Pastikeun h3 resolvable ti root proyék
  const h3Check = spawnSync('node', ['-e', "require.resolve('h3')"], { cwd })
  if (h3Check.status !== 0) {
    console.log(chalk.gray('   Installing h3 (needed by the generated server entry)...'))
    try {
      execSync('npm install h3', { stdio: 'inherit', cwd })
    } catch (err) {
      console.error(chalk.red.bold('\n❌ Failed to install h3:'))
      console.error(chalk.red(err.message))
      return
    }
  }

  // 4. Generate worker entry — salawasna ditulis ulang (murni glue code)
  const generatedDir = path.join(cwd, '.solid-vue')
  if (!fs.existsSync(generatedDir)) fs.mkdirSync(generatedDir, { recursive: true })

  const serverEntryPath = path.join(distDir, 'server-entry.mjs')
  const workerEntryPath = path.join(generatedDir, 'worker-entry.mjs')

  if (fs.existsSync(serverEntryPath)) {
    fs.writeFileSync(workerEntryPath, `// Auto-generated by "solid-vue deploy". Do not edit by hand.
import { app } from '../dist/server-entry.mjs'

export default {
  fetch(request, env, ctx) {
    const url = new URL(request.url)
    url.pathname = url.pathname.replace(/^\\/api/, '') || '/'
    return app.fetch(new Request(url, request), env, ctx)
  }
}
`)
  } else {
    fs.writeFileSync(workerEntryPath, `// Auto-generated by "solid-vue deploy". No API routes found — serving static assets only.
export default {
  fetch(request, env, ctx) {
    return env.ASSETS.fetch(request)
  }
}
`)
  }

  // 5. Generate wrangler.jsonc — ngan lamun can aya
  const wranglerPath = path.join(cwd, 'wrangler.jsonc')
  if (!fs.existsSync(wranglerPath)) {
    const workerName = (pkg.name || 'solid-vue-app')
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')

    const today = new Date().toISOString().slice(0, 10)

    fs.writeFileSync(wranglerPath, `{
  "name": "${workerName}",
  "main": ".solid-vue/worker-entry.mjs",
  "compatibility_date": "${today}",
  "assets": {
    "directory": "./dist",
    "binding": "ASSETS",
    "not_found_handling": "single-page-application",
    "run_worker_first": ["/api/*"]
  }
}
`)
    console.log(chalk.gray(`   Generated wrangler.jsonc (worker name: "${workerName}")`))
  } else {
    console.log(chalk.gray('   wrangler.jsonc already exists — leaving it untouched.'))
  }

  // 6. Tambihkeun .solid-vue/ ka .gitignore, lamun aya .gitignore-na
  const gitignorePath = path.join(cwd, '.gitignore')
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf-8')
    if (!content.includes('.solid-vue')) {
      fs.appendFileSync(gitignorePath, '\n.solid-vue/\n')
    }
  }

  // 7. Cek login Cloudflare
  console.log(chalk.gray('\n   Checking Cloudflare login...'))
  const whoami = spawnSync('npx', ['wrangler', 'whoami'], { cwd, encoding: 'utf-8' })
  if (whoami.status !== 0 || /not authenticated|not logged in/i.test(whoami.stdout + whoami.stderr)) {
    console.log(chalk.yellow('\n⚠️  You are not logged in to Cloudflare yet.'))
    console.log(chalk.white('   Run this, then re-run the deploy command:'))
    console.log(chalk.cyan('   npx wrangler login'))
    return
  }

  // 8. Deploy
  console.log(chalk.blue.bold('\n   Deploying...'))
  try {
    execSync('npx wrangler deploy', { stdio: 'inherit', cwd })
  } catch {
    console.error(chalk.red.bold('\n❌ wrangler deploy failed. See the output above for details.'))
    return
  }

  console.log(chalk.green.bold('\n✅ Deployed successfully!'))
}